### ISSUE TITLE
Bug in ordering by month

### ISSUE THREAD

**Issue by chriscoyier** [CSS-Tricks/conferences#136]
<img width="1267" alt="Screen Shot 2019-06-28 at 1 08 01 PM" src="https://user-images.githubusercontent.com/69156/60368476-d3963180-99a5-11e9-8aac-cc52ea006e36.png">

This 2020 conf is showing before 2019 confs this time of year just because "May" is before "July". We need to get smarter with how things are ordered.

**Comment by fimion** [comment]
Would it be helpful to simply look at the current year and the following year? you could likely have a function that just makes an array that returns the current year and the next year, then add an extra loop to go through that when generating things. 

I suppose it'd also be useful to add a year to either the month header name or as an extra header section.

**Comment by chriscoyier** [comment]
@fimion that sounds like a great idea. Got to help with that?

**Comment by fimion** [comment]
Yeah, I haven't worked with 11ty before but it looks pretty straight forward. Let me see if I can take a crack at it this week.
