### ISSUE TITLE
October 2019 conferences showing up for October 2020

### ISSUE THREAD

**Issue by ananyaneogi** [CSS-Tricks/conferences#169]
Here's an image for reference -

![Screenshot](https://user-images.githubusercontent.com/17353471/66206267-37c74080-e6cd-11e9-96ab-007303f077ac.png)

The issue seems to be in the condition where the conference dates is checked.

**Comment by ananyaneogi** [comment]
I went ahead and created a pr with the fix 😄

**Comment by chriscoyier** [comment]
Fix works great :)
