### ISSUE TITLE
UX: Should conference title linking go to conference detail page?

### ISSUE THREAD

**Issue by ecarlisle** [CSS-Tricks/conferences#217]
Hi!
When clicking  a conference title from the main page I was expecting to be taken to a detail page instead of directly to the conference site. That happens if I click the `*` icon, but wondered if the title should do the same. There is a direct link to the conference on each card. 

Happy to make a PR if that sounds like a plan.

**Comment by chriscoyier** [comment]
I don't think so on this one. Our "details page" is kinda lame. Maybe someday if we find a way to make it cool, but for now I think it makes more sense to link directly to the conference. 

I could potentially see being somehow more *clear* that that's what the links will do though, if there are more ideas there.
