### ISSUE TITLE
TODO: Link to JSON feed

### ISSUE THREAD

**Issue by chriscoyier** [CSS-Tricks/conferences#35]
There is one, there just isn't any link.

https://conferences.css-tricks.com/feed.json

**Comment by philhawksworth** [comment]
I reckon this should be good to close now that https://github.com/CSS-Tricks/conferences/pull/44 has been merged.

<img width="908" alt="screenshot 2019-02-14 at 16 03 39" src="https://user-images.githubusercontent.com/5865/52799703-4b586500-3072-11e9-8e0c-2ed5466297ef.png">

**Comment by chriscoyier** [comment]
gonzo
