### ISSUE TITLE
Add package-lock.json and dist/ to .gitignore

### ISSUE THREAD

**Issue by dunphyben** [CSS-Tricks/conferences#47]
Building locally adds a diff to 2 files immediately upon building:
![image](https://user-images.githubusercontent.com/5455826/52805665-ec77f900-303b-11e9-825f-2200f3b09e4b.png)
This is especially odd b/c `dist/` is already in the `.gitignore` file. 
![image](https://user-images.githubusercontent.com/5455826/52805930-93f52b80-303c-11e9-9908-84af7e4fdc84.png)
Is there an error somewhere in this causing corruption?

**Comment by chriscoyier** [comment]
I totally don't understand why dist/ files still go to Git when it's clearly in the .gitignore. It's just my ignorance. Feel free to fix if you know how!

**Comment by andwilr** [comment]
saw this and wanted to try my hand at fixing - let me know what you think!

**Comment by chriscoyier** [comment]
See @andwilr's PR ^^ for why we're keeping the lockfile. Otherwise a nice win here for removing that dang dist folder.
