### ISSUE TITLE
Persist grid/list view setting

### ISSUE THREAD

**Issue by Wilto** [CSS-Tricks/conferences#97]
Worth adding a <i>soupçon</i> of `localStorage` here?

**Comment by chriscoyier** [comment]
Seems good to me!

This is intriguing: https://developers.google.com/web/updates/2019/03/kv-storage, but it sorta feels like wide browser support for that isn't exactly around the corner so maybe localStorage is good for now.

**Comment by Wilto** [comment]
Closed by #100
