### ISSUE TITLE
Showing root/conf domains in conference links

### ISSUE THREAD

**Issue by Wilto** [CSS-Tricks/conferences#98]
![](https://user-images.githubusercontent.com/439942/56142685-192d8b80-5f6d-11e9-93b1-79270cb54e31.png)

We’re dropping the icon-only treatment for links to conference sites, but we don’t want to drop the entire url in there—the link pointing to `https://smashingconf.com/sf-2019/` should be `smashingconf.com →`.

Do we want this to be something new in the frontmatter:

```
---
title: Smashing Conference
url: https://smashingconf.com/sf-2019/
urltxt: SmashingConf.com
…
```

Or should I wire up a custom Eleventy filter that pulls the domain out of the `url` field? The former is quicker and gives us finer-grained control, the latter means one less thing to maintain.

**Comment by chriscoyier** [comment]
I'd rather keep it out of the front matter and extract it from the URL itself

**Comment by Wilto** [comment]
Done deal. Limits us a little bit on details like title case, but seems pretty solid overall:

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/439942/56301590-22059500-6106-11e9-97ca-e136ff4821b1.png">
